update ci

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,109 +14,73 @@ on:
 
 jobs:
   # phase 1
-  list:
+  build-target:
     runs-on: ubuntu-latest
 
     outputs:
-      target_branch: ${{ steps.defaults.outputs.target_branch }}
-      version: ${{ steps.defaults.outputs.version }}
-      component_matrix: ${{ steps.set_matrix.outputs.matrix }}
+      target_branch: ${{ steps.build-target.outputs.target_branch }}
+      version: ${{ steps.build-target.outputs.version }}
+      docker_matrix: ${{ steps.build-target.outputs.docker_matrix }}
 
     steps:
-    - uses: actions/checkout@v4
-      with:
-        submodules: 'recursive'
+      # return error if secrets are missing
+      - name: Check secrets
+        run: |
+          [ -z "${{ secrets.GTHB_USER }}" ] && echo "Missing GTHB_USER secret" && exit 1
+          [ -z "${{ secrets.GTHB_PAT }}" ] && echo "Missing GTHB_PAT secret" && exit 1
 
-    - uses: viash-io/viash-actions/setup@v5
+      - uses: actions/checkout@v4
+        with:
+          submodules: 'recursive'
 
-    - name: Determine version tag from branch name
-      id: defaults
-      run: |
-        BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
+      - uses: viash-io/viash-actions/setup@v5
 
-        VERSION=${{ github.event.inputs.version }}
-        if [ -z "$VERSION" ]; then
-          VERSION="build-$BRANCH_NAME"
-        fi
-        echo "version=$VERSION" >> $GITHUB_OUTPUT
-
-        TARGET_BRANCH=${{ github.event.inputs.target_branch }}
-        if [ -z "$TARGET_BRANCH" ]; then
-          TARGET_BRANCH="build-$BRANCH_NAME"
-        fi
-        echo "target_branch=$TARGET_BRANCH" >> $GITHUB_OUTPUT
-
-    - name: Remove target folder from .gitignore
-      run: |
-        # allow publishing the target folder
-        sed -i '/^\/target.*/d' .gitignore
-
-    - uses: viash-io/viash-actions/ns-build@v5
-      with:
-        config_mod: .functionality.version := '${{ steps.defaults.outputs.version }}'
-        parallel: true
-
-    - name: Deploy to target branch
-      uses: peaceiris/actions-gh-pages@v4
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: .
-        publish_branch: ${{ steps.defaults.outputs.target_branch }}
-
-    - id: ns_list
-      uses: viash-io/viash-actions/ns-list@v5
-      with:
-        platform: docker
-        src: src
-        format: json
-
-    - id: set_matrix
-      run: |
-        echo "matrix=$(jq -c '[ .[] | 
-          { 
-            "name": (.functionality.namespace + "/" + .functionality.name),
-            "dir": .info.config | capture("^(?<dir>.*\/)").dir
-          }
-        ]' ${{ steps.ns_list.outputs.output_file }} )" >> $GITHUB_OUTPUT
+      - uses: viash-io/viash-actions/project/build-target@viash-0.9
+        id: build-target
+        with:
+          target_branch: ${{ github.event.inputs.target_branch }}
+          version: ${{ github.event.inputs.version }}
+      
+      - name: Deploy to target branch
+        uses: peaceiris/actions-gh-pages@v4
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_branch: ${{ steps.build-target.outputs.target_branch }}
+          publish_dir: .
 
   # phase 2
-  build:
-    needs: list
+  build-docker:
+    needs: build-target
 
     runs-on: ubuntu-latest
 
     strategy:
       fail-fast: false
       matrix:
-        component: ${{ fromJson(needs.list.outputs.component_matrix) }}
+        component: ${{ fromJson(needs.build-target.outputs.docker_matrix) }}
 
     steps:
-    # Remove unnecessary files to free up space. Otherwise, we get 'no space left on device.'
-    - uses: data-intuitive/reclaim-the-bytes@v2
-    
-    - uses: actions/checkout@v4
+      # Remove unnecessary files to free up space. Otherwise, we get 'no space left on device.'
+      - uses: data-intuitive/reclaim-the-bytes@v2
+      
+      - uses: actions/checkout@v4
 
-    - uses: viash-io/viash-actions/setup@v5
+      - uses: viash-io/viash-actions/setup@v5
+          
+      - name: Login to container registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ secrets.GTHB_USER }}
+          password: ${{ secrets.GTHB_PAT }}
 
-    - name: Build container
-      uses: viash-io/viash-actions/ns-build@v5
-      with:
-        config_mod: .functionality.version := '${{ needs.list.outputs.version }}'
-        platform: docker
-        src: ${{ matrix.component.dir }}
-        setup: build
-        
-    - name: Login to container registry
-      uses: docker/login-action@v3
-      with:
-        registry: ghcr.io
-        username: ${{ secrets.GTHB_USER }}
-        password: ${{ secrets.GTHB_PAT }}
+      - name: Build container
+        run: |
+          if ${{ matrix.component.runner}} == "executable"; then
+            extra_flag="---engine docker"
+          fi
 
-    - name: Push container
-      uses: viash-io/viash-actions/ns-build@v5
-      with:
-        config_mod: .functionality.version := '${{ needs.list.outputs.version }}'
-        platform: docker
-        src: ${{ matrix.component.dir }}
-        setup: push
+          # todo: enable cachedbuild?
+          # eval ${{matrix.component.executable}} ---setup pull ---verbose $extra_flag
+          eval ${{matrix.component.executable}} ---setup build ---verbose $extra_flag
+          eval ${{matrix.component.executable}} ---setup push ---verbose $extra_flag
